### ISSUE TITLE
SD card pins documentation

### ISSUE THREAD

**Issue by jstkatz** [AutomationDirect/P1AM-Examples#1]
I've been trying to determine which MKR header pins are available. The P1AM user manual doesn't show the pins used by the sd card so I checked the datalogger example here. The read me for that seems to have the wrong pins called out for the SDcard. From the P1AM_REVA schematic it looks like the SDcard pins aren't reused anywhere.

**Comment by AdamCummick** [comment]
That definitely a typo, the P1AM-100 doesn't use any header pins for the SD card. We are working on getting that info corrected. Thanks for the catch on this!

The P1AM Base Controller uses MKR header pins 8, 9, 10, A3, and A4. 8, 9 , and 10 can be shared by multiple SPI devices, but A3 and A4 must not be used anywhere else. More info here: https://facts-engineering.github.io/modules/P1AM-100/P1AM-100.html

**Comment by jstkatz** [comment]
I don't know if there is a better space to mention it but I'm also noticing pin 5 is absent from the tables on page 2-12 of the pdf user manual

**Comment by AdamCummick** [comment]
Page 2-12 looks like it's only for the P1AM-GPIO shield. We only list the pins that go to the terminal block on that page. 5 is one of the pins omitted from the terminal block on that product.

**Comment by ADCCOMMNG** [comment]
Readme.md file has been updated.
