### ISSUE TITLE
Out of Memory error

### ISSUE THREAD

**Issue by Jeff-9802** [AutomationDirect/P1AM-Examples#2]
When I compile the P1AM-100_ModbusTCP_KitchenSink sketch, I get the following error.  I have not made any changes to the sketch.

cc1plus.exe: out of memory allocating 1677721600 bytes

**Comment by AdamCummick** [comment]
Can you go to "Tools" and confirm for the board you have selected the "P1AM-100"?

**Comment by Jeff-9802** [comment]
I do have the P1AM-100 selected.

I was able to fix the problem by copying the 137 lines of code from GitHub and overwriting everything in the sketch.  I did it in small segments, but it did not work until I replaced every single line in the sketch.
